service: codemotion23-webhooks-js-example

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  profile: fliuzzi-playground
  region: eu-north-1
  versionFunctions: false
  httpApi:
    shouldStartNameWithService: true

functions:
  web:
    handler: src/web.handler
    events:
      - httpApi: '*'

custom:
  resource_prefix: ${self:service}-${sls:stage}-
